# config/routes.yaml

controllers:
  resource: ../src/Controller/
  type: annotation

# Uncomment below if you use routes defined in YAML
# framework:
#   resource: 'kernel:loadRoutes'
#   type: service
